import { describe, it, expect } from 'vitest';
import { AiTailorService } from '../services/ai-tailor.js';
import { AtsScorerService } from '../services/ats-scorer.js';
import { ResumeBullet, AtsScoreReport } from '../types/index.js';

describe('Phase 1: Closed-Loop ATS Evaluator-Optimizer Engine', () => {
  const atsScorer = new AtsScorerService();
  const aiTailor = new AiTailorService();

  const mockJobDesc = `
Senior Distributed Systems Engineer | Stripe
Requirements:
- Strong experience in Go or Python
- Hands-on expertise with Kubernetes, Docker, and AWS
- Experience with distributed caching using Redis and relational databases like PostgreSQL
- Proven track record maintaining 99.99% uptime SLAs
- Deep knowledge of microservices, distributed systems, and REST APIs
`;

  const initialResume = `
Jane Doe
jane@example.com
github.com/janedoe/raft-kv

EDUCATION
B.S. in Computer Science | University of California, Berkeley | 2024

SKILLS
Languages & Frameworks: Python, JavaScript, HTML/CSS, SQL

EXPERIENCE
Software Engineer | Tech Corp | 2023 - Present
• Worked on backend APIs using Python and helped database performance.
• Responsible for server deployments and fixing system bugs.

PROJECTS
Distributed Raft Engine | Go, Redis
github.com/janedoe/raft-kv
• Built a key-value store in Go with consensus protocol and 100% test coverage.
`;

  const initialBullets: ResumeBullet[] = [
    {
      id: 'b-1',
      section: 'Experience',
      organization: 'Tech Corp',
      role: 'Software Engineer',
      originalText: 'Worked on backend APIs using Python and helped database performance.',
    },
    {
      id: 'b-2',
      section: 'Experience',
      organization: 'Tech Corp',
      role: 'Software Engineer',
      originalText: 'Responsible for server deployments and fixing system bugs.',
    },
  ];

  it('calculates accurate baseline ATS score prior to closed-loop mutations', () => {
    const baselineReport = atsScorer.analyze(initialResume, mockJobDesc);

    // Initial passive bullets lack production keywords (Docker, Kubernetes, AWS, 99.99% SLA)
    expect(baselineReport.overallScore).toBeLessThan(75);
    expect(baselineReport.keywords.some((k) => k.keyword === 'Kubernetes' && !k.foundInResume)).toBe(true);
    expect(baselineReport.actionVerbStrength.weakCount).toBeGreaterThan(0);
  });

  it('closed-loop simulator verifies that applying optimized STAR diffs achieves score >= 88 and significant gain', () => {
    const baselineReport = atsScorer.analyze(initialResume, mockJobDesc);

    // Simulated high-tier tailored diffs generated by the engine
    const mockOptimizedDiffs = [
      {
        id: 'b-1',
        originalText: initialBullets[0].originalText,
        tailoredText:
          'Architected 8 asynchronous microservices and REST APIs using Go and PostgreSQL, deploying Redis caching to slash P99 query latency by 52% across 2M daily requests.',
        status: 'accepted' as const,
        injectedKeywords: ['Go', 'PostgreSQL', 'Redis', 'Microservices', 'REST APIs'],
        scoreGain: 18,
      },
      {
        id: 'b-2',
        originalText: initialBullets[1].originalText,
        tailoredText:
          'Orchestrated automated CI/CD deployment pipelines on AWS using Docker & Kubernetes, sustaining 99.99% uptime SLAs across multi-region distributed systems.',
        status: 'accepted' as const,
        injectedKeywords: ['AWS', 'Docker', 'Kubernetes', 'CI/CD', 'Distributed Systems'],
        scoreGain: 16,
      },
    ];

    // Apply diffs and run closed-loop scoring
    let mutatedText = initialResume;
    for (const diff of mockOptimizedDiffs) {
      mutatedText = mutatedText.replace(diff.originalText, diff.tailoredText);
    }

    const verifiedReport = atsScorer.analyze(mutatedText, mockJobDesc);

    expect(verifiedReport.overallScore).toBeGreaterThanOrEqual(88);
    expect(verifiedReport.keywords.find((k) => k.keyword === 'Kubernetes')?.foundInResume).toBe(true);
    expect(verifiedReport.keywords.find((k) => k.keyword === 'Redis')?.foundInResume).toBe(true);
    expect(verifiedReport.keywords.find((k) => k.keyword === 'Docker')?.foundInResume).toBe(true);
    expect(verifiedReport.keywords.find((k) => k.keyword === 'Postgresql' || k.keyword === 'PostgreSQL')?.foundInResume).toBe(true);
    expect(verifiedReport.productionExperienceAudit.productionKeywordsFound.length).toBeGreaterThanOrEqual(4);
    expect(verifiedReport.actionVerbStrength.strongCount).toBeGreaterThanOrEqual(2);
    expect(verifiedReport.actionVerbStrength.weakCount).toBe(0);

    // Score gain must be positive and significant
    const netGain = verifiedReport.overallScore - baselineReport.overallScore;
    expect(netGain).toBeGreaterThanOrEqual(18);
  });

  it('aiTailor returns fallback_rule_based metadata with authentic baseline when offline / no key', async () => {
    const baselineReport = atsScorer.analyze(initialResume, mockJobDesc);

    const result = await aiTailor.tailorBulletsWithAi(
      initialBullets,
      mockJobDesc,
      baselineReport,
      'Senior Distributed Systems Engineer',
      'Stripe',
      {
        provider: 'gemini',
        apiKey: '', // No key
        model: 'gemini-3.5-flash-lite',
      }
    );

    expect(result.usedAi).toBe(false);
    expect(result.loopStatus).toBe('fallback_rule_based');
    expect(result.baselineAtsScore).toBe(baselineReport.overallScore);
    expect(result.verifiedAtsScore).toBe(baselineReport.overallScore);
    expect(result.scoreGain).toBe(0);
  });
});
